# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trim <- function(s) {
    .Call(`_rim_trim`, s)
}

checkCommand <- function(command) {
    .Call(`_rim_checkCommand`, command)
}

