# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' RMaxima class for interacting with maxima
#'
#' This class provides access to maxima and in addition
#' provides convenience functions to execute special types of
#' commands
#'
#' @export
#' @examples
#' m <- new(RMaxima)
#'
#' m$execute("2+2")
#' m$loadModule("mac-tex-utilities")
NULL

